### ISSUE TITLE
Adding logo to title !

### ISSUE THREAD

**Issue by AdityaTeltia** [Script-Winter-of-Code/website#39]
The title with globe in front makes the website dull. Logo alongside the title will make the website stand-out .
![difference swoc](https://user-images.githubusercontent.com/67232537/97213035-29235e00-17e7-11eb-8799-4279e0ef04c7.PNG)

**Comment by godslayer201** [comment]
@AdityaTeltia thank you for bringing it to our attention. Will would rectify it. 

Looking forward to seeing you at SWoC!

**Comment by AdityaTeltia** [comment]
Sure ! I would love to be part of it .

**Comment by AdityaTeltia** [comment]
Actually i have added the above feature in my local file can i make make a pull request for the same 🙋‍♂️

**Comment by godslayer201** [comment]
@AdityaTeltia no,my apologies,the web team is working on it. You will get your chance during SWoC :)

**Comment by godslayer201** [comment]
@AdityaTeltia if you feel you can make any other enhancements,feel free to open a PR/issue

**Comment by AdityaTeltia** [comment]
Ok thanks 😊 looking forward for SWOC.
